// Configuración de Info Autos API
module.exports = {
  ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NjMwOTQwNSwianRpIjoiYTRiY2U5NTQtYzUxYi00NDAyLTllYWUtZTBiOTE4NDViMzVkIiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5Ijo1MzcsIm5iZiI6MTc1NjMwOTQwNSwiY3NyZiI6IjgxMGM1ZDNiLTM3MDUtNDNiYy04NGJjLTBmM2Q3Y2YyOTg1YSIsImV4cCI6MTc1NjMxMzAwNSwicm9sZXMiOlt7ImlkIjoxOSwibmFtZSI6IkRlc2Fycm9sbG8ifSx7ImlkIjoxMCwibmFtZSI6IkV4dHJhcyJ9LHsiaWQiOjksIm5hbWUiOiJNb2RlbG9zIn1dfQ.nOHl-v9O6GvLgI12HPXh6tBTSEv79XtEaoIyVwsrrEg",
  REFRESH_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1NjMwOTQwNSwianRpIjoiMGM3NTNjNWUtNzNjNS00MWIxLTg3ZDQtZTA1ODY1NWI2NGRiIiwidHlwZSI6InJlZnJlc2giLCJpZGVudGl0eSI6NTM3LCJuYmYiOjE3NTYzMDk0MDUsImNzcmYiOiJhZjFhMDIwOS02MjljLTQyN2QtOTJmNC1iNGI1NzA2ZWUyMDIiLCJleHAiOjE3NTYzOTU4MDUsInJvbGVzIjpbeyJpZCI6MTksIm5hbWUiOiJEZXNhcnJyb2xsbyJ9LHsiaWQiOjEwLCJuYW1lIjoiRXh0cmFzIn0seyJpZCI6OSwibmFtZSI6Ik1vZGVsbyJ9XX0.1rxJp4s8A77q21WwYO9REnktqTG67TCY_-bW1yxntTg",
  
  // Credenciales para renovar tokens automáticamente
  USERNAME: process.env.INFOAUTOS_USERNAME || "gdentice@agpgroup.com.ar",
  PASSWORD: process.env.INFOAUTOS_PASSWORD || "4Eiqt6pxuAC1XmM0",
  
  // URLs de autenticación
  LOGIN_URL: "https://api.infoauto.com.ar/cars/auth/login",
  REFRESH_URL: "https://api.infoauto.com.ar/cars/auth/refresh"
};
